### ISSUE TITLE
update to angular 18

### ISSUE THREAD

**Issue by whyvrafvr** [fairhive-labs/poln-app#47]
https://angular.dev/update-guide

**Comment by moudgalya1223** [comment]
hello @whyvrafvr  yoou can assign it to me will upgrade thanks 
@whyvrafvr

**Comment by whyvrafvr** [comment]
Done ✅ @moudgalya1223 
Will check your PR 🤗

**Comment by whyvrafvr** [comment]
> hello @whyvrafvr please a have look at the pr

thx 🙏 comments in PR

**Comment by whyvrafvr** [comment]
Why did you open a new PR ?
PR #49 does not work. How did you update `Angular Material` ?

**Comment by whyvrafvr** [comment]
updated to Angular 17

**Comment by whyvrafvr** [comment]
Hey @s4m5ep10l, I will complete in the afternoon -quiet busy on other stuff-.
Could you please review asap buddy (in the morning for you 😄 )

**Comment by whyvrafvr** [comment]
**TODO:**
- [ ] fix error messages running `ng test`
- [ ] npm update to latest (`npm audit`)

**Comment by s4m5ep10l** [comment]
here we go

**Comment by s4m5ep10l** [comment]
looks like you've also updated the `deployment` with github pages. nice
